---
# System configuration
git_username: "{{ current_user }}"
git_fullname: "{{ full_name }}"
git_email: "{{ email }}"
hostname: "{{ current_user }}"

# Applications
user_applications:
  - battery-monitor
  - indicator-keylock
  - fzf
  - google-chrome-stable
  - putty
  - filezilla
  - toolboxapp   # Jetbrains stack

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras:
  - java
  - nodejs
  - ruby
  - docker
  - virtualbox
  - sublime
  - atom
  - terminator

# Extra packages (add here any OS package you need),
# keep in mind your OS distribution for some packages.
extra_packages:
  - htop
  - gparted
  - liberror-perl
  - libqt5x11extras5
  - libsdl1.2debian
  - python-pip
  - pulseaudio
  - meld
  - vim
  - synapse
  - autojump

# Enable basic server security configuration
extra_security_enabled: true

firewall_enabled: false
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "111"
  - "443"
  - "1110"
  - "1197"
  - "2049"
  - "2222"
  - "3306"
  - "4045"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
  - "9000"
  - "9200"
  - "32764"
  - "32765"
  - "32766"
  - "32767"
  - "32768"
  - "32769"
firewall_allowed_udp_ports:
  - "111"
  - "1110"
  - "1197"
  - "2049"
  - "3306"
  - "4045"
  - "9000"
  - "32764"
  - "32765"
  - "32766"
  - "32767"
  - "32768"
  - "32769"
firewall_log_dropped_packets: true
firewall_disable_firewalld: true
firewall_disable_ufw: true

# PHP Configuration. Currently-supported versions: 5.6, 7.0, 7.1.
# See version-specific notes: http://docs.drupalvm.com/en/latest/configurations/php/
php_version: "7.0"
php_packages_extra:
  - "php{{ php_version }}-bcmath"
  - "php{{ php_version }}-bz2"
  - "php{{ php_version }}-ldap"
  - "php{{ php_version }}-mysql"
  - "php{{ php_version }}-pgsql"
  - "php{{ php_version }}-soap"
php_enable_webserver: false
php_install_recommends: no
php_memory_limit: "192M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/sendmail -t -i"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"

php_enable_php_fpm: false
# We must set the port other than 9000 to avoid collisions wwith XDebug
php_fpm_listen: "127.0.0.1:9090"

composer_path: /usr/bin/composer
composer_home_path: "/home/{{ current_user }}/.composer"
composer_home_owner: "{{ current_user }}"
composer_home_group: "{{ current_user }}"
composer_global_packages:
  - { name: hirak/prestissimo, release: '^0.3' }
  - { name: deployer/deployer, release: '^4' }
  - { name: consolidation/robo, release: '^1' }

# Node.js configuration (if enabled above).
# Valid examples: "0.10", "0.12", "4.x", "5.x".
# NOTE! Use 6.x version for Ubuntu 17.10.
nodejs_version: "6.x"
nodejs_npm_global_packages:
  - name: bower
  - name: grunt
  - name: gulp
  - name: yo

nodejs_install_npm_user: "{{ current_user }}"
npm_config_prefix: "/home/{{ current_user }}/.npm-global"

# Ruby Configuration (if enabled above).
ruby_install_gems_user: "{{ current_user }}"
ruby_install_gems:
  - compass
  - bourbon
  - neat
  - bitters
  - refills

# Vagrant
vagrant_version : '2.0.2'
vagrant_platform : x86_64

# VirtualBox
virtualbox_apt_package: virtualbox-5.1

# Atom
atom_configuration:
  - username: "{{ current_user }}"
    atom_packages:
      - minimap
      - linter
      - atom-beautify
      - file-icons
    atom_config:
      "*":
        core:
          projectHome: "/home/{{ current_user }}/workspace"
        editor:
          showIndentGuide: true
          showInvisibles: true

# Oh-My-ZSH
# Important: oh-my-zsh is installed per user so you need to specify the users to install it for.
oh_my_zsh_configuration:
  - username: "{{ current_user }}"
    oh_my_zsh:
      theme: bureau
      plugins:
        - git
        - vagrant
        - Composer
        - vi-mode
        - vi-interaction
        - autojump
