---
- hosts: all
  become: yes

  vars_files:
    - vars/main.yml
    - default.config.yml

  pre_tasks:
    - include: tasks/hostname.yml

    - include: tasks/init-debian.yml
      when: ansible_os_family == 'Debian'
      static: no

    - name: Ensure PHP version -specific workspace directory exists.
      file:
        path: "/root/php{{ php_version }}"
        state: directory
        mode: 0775

    - name: Ensure SSH server is installed
      apt: name=openssh-server state=installed
      when: extra_security_enabled

  roles:
    # Essential roles.
    - geerlingguy.git
    - geerlingguy.postfix
    - geerlingguy.php
    - geerlingguy.php-pecl
    - geerlingguy.composer
    - geerlingguy.daemonize
    - geerlingguy.java
    - andrewrothstein.vagrant
    - geerlingguy.nfs
    - role: gantsign.oh-my-zsh
      users: oh_my_zsh_configuration

    # Virtualization.
    - { role: geerlingguy.docker, when: '"docker" in installed_extras' }
    - { role: FGtatsuro.virtualbox, when: '"virtualbox" in installed_extras' }

    # Languages.
    - { role: geerlingguy.nodejs, when: '"nodejs" in installed_extras' }
    - { role: geerlingguy.ruby, when: '"ruby" in installed_extras' }

    # Editors and tools.
    - role: gantsign.atom
      users: atom_configuration
      when: '"atom" in installed_extras'
    - { role: KeyboardInterrupt.sublime-text-3, when: '"sublime" in installed_extras' }
    - { role: configure-sublime, when: '"sublime" in installed_extras' }
    - { role: gantsign.terminator, when: '"terminator" in installed_extras' }

    # Roles for security and stability.
    - { role: geerlingguy.firewall, when: firewall_enabled }
    - { role: geerlingguy.security, when: extra_security_enabled }

    # Post-execution tasks.
    - { role: post-exec }
