---
- src: andrewrothstein.vagrant
  version: 'v1.0.13'
- src: FGtatsuro.virtualbox
- src: gantsign.atom
  version: 1.3.1
- src: gantsign.terminator
  version: 1.0.0
- src: gantsign.oh-my-zsh
  version: 1.2.1
- src: geerlingguy.docker
  version: 2.1.0
- src: geerlingguy.composer
  version: 1.6.1
- src: geerlingguy.daemonize
  version: 1.2.0
- src: geerlingguy.firewall
  version: 2.3.0
- src: geerlingguy.git
  version: 1.4.0
- src: geerlingguy.java
  version: 1.7.4
- src: geerlingguy.nfs
  version: 1.2.1
- src: geerlingguy.nodejs
  version: 4.1.2
- src: geerlingguy.pip
  version: 1.2.0
- src: geerlingguy.php
  version: 3.5.0
- src: geerlingguy.php-pecl
  version: 1.4.0
- src: geerlingguy.postfix
  version: 2.0.0
- src: geerlingguy.ruby
  version: 2.4.3
- src: geerlingguy.security
  version: 1.5.0
- src: KeyboardInterrupt.sublime-text-3
  version: 'v1.0.0'
