---
- src: geerlingguy.docker
  version: 2.0.1
- src: geerlingguy.composer
  version: 1.6.1
- src: geerlingguy.daemonize
  version: 1.1.1
- src: geerlingguy.firewall
  version: 2.1.1
- src: geerlingguy.git
  version: 1.2.1
- src: geerlingguy.java
  version: 1.7.4
- src: geerlingguy.nodejs
  version: 4.0.0
- src: geerlingguy.php
  version: 3.4.4
- src: geerlingguy.php-pecl
  version: 1.3.0
- src: geerlingguy.php-xdebug
  version: 2.3.1
- src: geerlingguy.postfix
  version: 1.1.0
- src: geerlingguy.ruby
  version: 2.4.2
- src: geerlingguy.security
  version: 1.5.0
