---
- name: Update apt cache if needed.
  apt: update_cache=yes cache_valid_time=86400

- name: Install required dependencies.
  apt: "name={{ item }} state=installed"
  with_items:
    - curl
    - python-apt
    - python-pycurl
    - sudo
    - unzip
    - make

- name: Ensure necessary groups exist.
  group: "name={{ item }} state=present"
  with_items:
    - admin
    - dialout

- name: Ensure user is in admin group.
  user: "name={{ current_user }} append=yes groups=admin"

- name: Configure /etc/mailname.
  copy:
    content: "{{ hostname_fqdn }}\n"
    dest: /etc/mailname

# @TODO Remove this once this is fixed https://github.com/geerlingguy/ansible-role-java/issues/48
- name: Hack geerlingguy.java role for Ubuntu 17.10
  template:
    src: Ubuntu-17.10.j2
    dest: "{{ playbook_dir }}/roles/geerlingguy.java/vars/Ubuntu-17.10.yml"
    owner: "{{ current_user }}"
    group: "{{ current_user }}"
    mode: 0744

- name: Add an apt key for VirtualBox when using Ubuntu 17.10
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: A2F683C52980AECF
  when: 'ansible_distribution == "Ubuntu" and ansible_distribution_version == "17.10"'

- name: Register profile.d scripts.
  blockinfile:
    dest: "/home/{{ current_user }}/.profile"
    block: "{{ lookup('template', 'profile.j2') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR PROFILES"
  become: no

- name: Ensure .temp directory is clean
  file:
    state: "{{ item }}"
    path: "{{ temp_directory }}/"
    mode: '0744'
  with_items:
    - absent
    - directory
  become: no

- name: Allow root to run X display from terminal.
  template:
    src: xhost.desktop.j2
    dest: "/home/{{ current_user }}/.config/autostart/xhost.desktop"
    owner: "{{ current_user }}"
    group: "{{ current_user }}"
    mode: 0664
  become: no
