---
  # Install material design theme and icons
  - name: Add Adapta GTK Material Design theme
    apt_repository: repo='ppa:tista/adapta'
    when: tweaks_use_material_design == true

  - name: Install Adapta GTK theme
    apt: name=adapta-gtk-theme state=installed
    when: tweaks_use_material_design == true

  - name: Add MonoDark Flattr icons
    git:
      repo: https://github.com/EmptyStackExn/mono-dark-flattr-icons
      dest: /usr/share/icons/mono-dark-flattr-icons
      clone: yes
      update: yes
      accept_hostkey: yes
    when: tweaks_use_material_design == true

  - name: Disable guest account
    lineinfile:
      dest: /etc/lightdm/lightdm.conf.d/99-no-guest.conf
      create: yes
      line: "[SeatDefaults]\nallow-guest=false\n"
      mode: 0744
    when: tweaks_disable_guest_account == true

  - name: You shall not 'sudo' in vane
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: "^Defaults *env_reset"
      line: "Defaults    env_reset,insults"
      validate: "visudo -cf %s"
    when: tweaks_sudo_insults == true

  - name: Add alias to run last typed command as sudo
    lineinfile:
      dest: "/home/{{ current_user }}/.bashrc"
      line: "alias dude='sudo $(history -p \\!\\!)'"
    when: tweaks_disable_guest_account == true

  - name: Set up Git global configuration
    template:
      src: .gitconfig.j2
      dest: "/home/{{ current_user }}/.gitconfig"
      owner: "{{ current_user }}"
      group: "{{ current_user }}"
      mode: 0744

  - name: Increment file watcher size up to 512Kb
    lineinfile:
      dest: /etc/sysctl.d/99-inotify.conf
      create: yes
      line: "fs.inotify.max_user_watches = 524288"
      mode: 0744

  - name: Reload sysctl configuration
    command: sysctl -p --system
