---
  - name: Add libraries dependencies
    apt: "name={{ item.name }} state=installed"
    with_items:
      # Google Chrome dependencies
      - { name: libindicator7, when: '"google-chrome" in user_applications' }
      - { name: libappindicator1, when: '"google-chrome" in user_applications' }
      # Battery Monitor dependencies
      - { name: python3, when: '"battery-monitor" in user_applications' }
      - { name: python3-gi, when: '"battery-monitor" in user_applications' }
      - { name: libnotify-dev, when: '"battery-monitor" in user_applications' }
      - { name: acpi, when: '"battery-monitor" in user_applications' }

  - name: Add Battery Monitor repository.
    apt_repository: repo='ppa:maateen/battery-monitor'
    when: '"battery-monitor" in user_applications'

  - name: Add Google Chrome repository key
    apt_key:
      url: https://dl-ssl.google.com/linux/linux_signing_key.pub
      state: present
    when: '"google-chrome" in user_applications'

  - name: Register Google Chrome repository
    apt_repository:
      repo: deb http://dl.google.com/linux/chrome/deb/ stable main
      state: present
      filename: "google-chrome-stable"
    when: '"google-chrome" in user_applications'

  - name: If installed, make Guake run on system startup
    file:
      src: /usr/share/applications/guake.desktop
      dest: /etc/xdg/autostart/guake.desktop
      state: link
    when: '"guake" in user_applications'

  - name: Register KeyLocks repository
    apt_repository: repo='ppa:tsbarnes/indicator-keylock'
    when: '"indicator-keylock" in user_applications'

  - name: Install end-user applications
    apt: "name={{ item }} state=installed"
    with_items: "{{ user_applications | list }}"
    when: user_applications | length

  - name: Allow open external links in Google Chrome
    lineinfile:
      path: "/home/{{ current_user }}/.local/share/applications/google-chrome.desktop"
      state: present
      regexp: "^Exec=/opt/google/chrome/chrome$"
      line: "Exec=/opt/google/chrome/chrome %U"
    when: '"google-chrome" in user_applications'

  - name: Install extra packages for Putty
    apt: "name={{ item }} state=installed"
    with_items:
      - putty-doc
      - putty-tools
    when: '"putty" in user_applications'

  - name: Install Filezilla extras
    apt: "name=filezilla-common state=installed"
    when: '"filezilla" in user_applications'
