---
- name: install fzf
  script: "/home/{{ current_user }}/.fzf/install --all --64"
  become: no

- name: install toolboxapp
  script: '{{ temp_directory }}/jetbrains-toolbox-{{ toolbox_version }}/jetbrains-toolbox'
  become: no