---
- name: Ensure preferences are set in place
  template:
    src: Preferences.sublime-settings.j2
    dest: "/home/{{ current_user }}/.config/sublime-text-3/Packages/User/Preferences.sublime-settings"
    owner: "{{ current_user }}"
    group: "{{ current_user }}"
    mode: 0744

- name: Check if Package Control is not installed
  stat: path="/home/{{ current_user }}/.config/sublime-text-3/Installed Packages/Package Control.sublime-package"
  register: spc
  when: 'spc.stat.exists == true'

- name: Download Package Control binary
  get_url:
    url: 'https://packagecontrol.io/Package%20Control.sublime-package'
    dest: '/home/{{ current_user }}/.config/sublime-text-3/Installed Packages/Package Control.sublime-package'
    owner: '{{ current_user }}'
    group: '{{ current_user }}'
  register: spc_downloaded
  when: 'spc.stat.exists == false'

- name: Register packages for download
  template:
    src: Package_Control.sublime-settings.j2
    dest: "/home/{{ current_user }}/.config/sublime-text-3/Packages/User/Package Control.sublime-settings"
    owner: "{{ current_user }}"
    group: "{{ current_user }}"
    mode: 0744
    force: no
  when: 'spc.stat.exists == true or spc_downloaded.status == 200'
